_wandb:
    value:
        cli_version: 0.18.2
        m: []
        python_version: 3.12.6
        t:
            "1":
                - 5
                - 53
                - 55
            "2":
                - 5
                - 53
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.12.6
            "5": 0.18.2
            "8":
                - 3
                - 5
            "12": 0.18.2
            "13": windows-amd64
dataset:
    value: Dynamic Pricing Dataset
model:
    value: Random Forest Regressor
random_state:
    value: 42
test_size:
    value: 0.2
